[project]
name = "maie5532assignment2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cmake>=4.1.0",
    "scipy>=1.13.1",
    "tensorflow-model-optimization>=0.8.0",
    "tensorflow[and-cuda]>=2.18.1",
]
